### ISSUE TITLE
Star for Star

### ISSUE THREAD

**Issue by xentzenith** [Vilutfullin/Vilutfullin#1]
Hey thank you for following me, I followed you back can you just give star last 2 repository which is

https://github.com/xentzenith/x3nos

https://github.com/xentzenith/weather-final-project

I will yours too. Just drop link after starring.

**Comment by Vilutfullin** [comment]
Hi, I put 2 stars, if it's not too much trouble put it on my repositories  https://github.com/Vilutfullin?tab=repositories

**Comment by Vilutfullin** [comment]
You have friends who are software testers?  Let them subscribe to me, and I'll subscribe to them.

**Comment by xentzenith** [comment]
If you join conversation that I mentioned you, probably you can find it.

Also I starred your repositories as well.

**Comment by Vilutfullin** [comment]
I put stars on all of your repositories
